[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.38", features = ["parquet", "lazy", "csv", "partition_by", "json", "serde", "dtype-struct", "polars-io"] }
rayon = "1.9"
anyhow = "1"
serde_json = "1"

[dev-dependencies]
rand = "0.8"
